- name: Get docker registry credentials from Vault
  set_fact:
    address: "{{ lookup('hashi_vault', '{{ vault_lookup_base_info }} secret=service-repositories/data/{{ docker_registries_vault_paths }}:address') }}"
    password: "{{ lookup('hashi_vault', '{{ vault_lookup_base_info }} secret=service-repositories/data/{{ docker_registries_vault_paths }}:password') }}"
    username: "{{ lookup('hashi_vault', '{{ vault_lookup_base_info }} secret=service-repositories/data/{{ docker_registries_vault_paths }}:username') }}"
  no_log: true

- name: Add credentials to dictionary
  set_fact:
    docker_registries: "{{ docker_registries|default([]) + [ {'address': address, 'password': password, 'username': username } ] }}"
  no_log: true
