---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all:!hypervisor
  gather_facts: false
  vars:
    ansible_libvirt_uri: >-
      {% if hostvars[groups['hypervisor'] | first].ansible_connection == 'ssh' %}qemu+ssh://{{ hostvars[groups['hypervisor'] | first].ansible_user }}@{{ hostvars[groups['hypervisor'] | first].ansible_host }}/system{% else %}qemu:///system{% endif %}
    ansible_connection: "community.libvirt.libvirt_qemu"
  serial: "{{ lookup('env', 'ANSIBLE_SERIAL') }}"
  tasks:
    - name: Include vars file
      include_vars:
        file: ./vars/main.yml

    - name: Get name of service
      set_fact:
        service_name: "{{ docker_compose_file.services | first }}"

    - name: Get infos on container
      community.docker.docker_container_info:
        name: "{{ service_id }}_{{ service_name }}_1"
      register: container_info

    - assert:
        that: container_info.container.State.Running == true

    - name: Get exposed port of service
      set_fact:
        service_port: "{{ docker_compose_file.services[service_name].ports[0] }}"

    - name: Wait for service port become available
      wait_for:
        port: "{{ docker_compose_file.services[service_name].ports[0] | split(':') | first }}"

