---
- name: "Create inventory with target host(s)"
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Set input parameter
      ansible.builtin.set_fact:
        skip_helper: true
      delegate_to: "{{ item }}"
      delegate_facts: True
      with_items: "{{ groups['all'] + ['localhost'] }}"

    - include_role:
        name: inventory_helper
      when: not skip_helper

- name: Uninstall docker
  hosts: target_hosts
  gather_facts: yes
  become: yes
  tasks:
    - name: "Include setup - uninstall"
      include_role:
        name: "setup"
        tasks_from: uninstall.yml
