---
- name: Prepare
  hosts: all:!hypervisor
  gather_facts: yes
  vars:
    ansible_libvirt_uri: >-
      {% if hostvars[groups['hypervisor'] | first].ansible_connection == 'ssh' %}qemu+ssh://{{ hostvars[groups['hypervisor'] | first].ansible_user }}@{{ hostvars[groups['hypervisor'] | first].ansible_host }}/system{% else %}qemu:///system{% endif %}
    ansible_connection: "community.libvirt.libvirt_qemu"
  become: yes
  serial: "{{ lookup('env', 'ANSIBLE_SERIAL') }}"
  tasks:
    - name: "Include setup - install"
      include_role:
        name: "setup"
        tasks_from: install.yml

    - name: Include vars file
      include_vars:
        file: ./vars/main.yml

    - name: "Include setup - install (service-1)"
      include_role:
        name: "use"
        tasks_from: deploy.yml
      vars:
        service_id: "{{ service_id_1 }}"
        docker_compose_file: "{{ docker_compose_file_1 }}"

    - name: "Include setup - install (service-2)"
      include_role:
        name: "use"
        tasks_from: deploy.yml
      vars:
        service_id: "{{ service_id_2 }}"
        docker_compose_file: "{{ docker_compose_file_2 }}"