---
- name: Debug
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - debug:
        var: hostvars

- name: Converge
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: "Include setup - uninstall"
      include_role:
        name: "setup"
        tasks_from: uninstall.yml
