---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all:!hypervisor
  gather_facts: false
  vars:
    ansible_libvirt_uri: >-
      {% if hostvars[groups['hypervisor'] | first].ansible_connection == 'ssh' %}qemu+ssh://{{ hostvars[groups['hypervisor'] | first].ansible_user }}@{{ hostvars[groups['hypervisor'] | first].ansible_host }}/system{% else %}qemu:///system{% endif %}
    ansible_connection: "community.libvirt.libvirt_qemu"
  serial: "{{ lookup('env', 'ANSIBLE_SERIAL') }}"
  tasks:
    - name: Do hello-world
      ansible.builtin.command: docker run hello-world
      become: yes
      register: result
      failed_when: false

    - assert:
        that:
          - result.rc == 2

